### ISSUE TITLE
Error building Spring Boot project

### ISSUE THREAD

**Issue by bkushigian** [bkushigian/major-gradle-plugin#3]
## Bug Inducing Input
I cloned the [Spring Boot Project](https://github.com/spring-projects/spring-boot/tree/e4380275e5344c82cacc6e92a6bced5d1595c2c6) and hooked into the `spring-boot-project:spring-boot-actuator-autoconfigure` subproject with the following diffs:

+ **build.gradle**:
    ```
    @@ -16,6 +16,7 @@ allprojects {
     	group "org.springframework.boot"

     	repositories {
    +    mavenLocal()
     		mavenCentral()
     		if (version.contains('-')) {
     			maven { url "https://repo.spring.io/milestone" }
    ```
+ **settings.gradle**:
    ```
    @@ -1,5 +1,6 @@
     pluginManagement {
     	repositories {
    +    mavenLocal()
     		mavenCentral()
     		gradlePluginPortal()
     		maven {
    ```

+ **spring-boot-project/spring-boot-actuator-autoconfigure/build.gradle:**
    ```
    @@ -6,8 +6,11 @@ plugins {
     	id "org.springframework.boot.conventions"
     	id "org.springframework.boot.deployed"
         id "org.springframework.boot.optional-dependencies"
    +  id "org.mutationtesting" version "0.0.1"
     }
    
    +apply plugin: "org.mutationtesting"
    +
    ```
Building with `./gradlew :spring-boot-project:spring-boot-actuator-autoconfigure:build --stacktrace` fails with the following relevant stack trace:

## Result
```
Caused by: java.lang.NullPointerException
        at org.mutationtesting.major.providers.ReflectionProvider.getField(ReflectionProvider.java:79)
        at org.mutationtesting.major.plugin.MajorPluginTaskListener.getEnv(MajorPluginTaskListener.java:131)
        at org.mutationtesting.major.plugin.MajorPluginTaskListener.finished(MajorPluginTaskListener.java:112)
```

**Comment by bkushigian** [comment]
Looking into Major, this stacktrace corresponds to the [following code](https://github.com/rjust/major/blob/master/mutator/src/main/java/org/mutationtesting/major/plugin/MajorPluginTaskListener.java#L130-L131) in MajorPluginTaskListener:
```java
    Enter enter = (Enter) ReflectionProvider.getField(javac, "enter");
    Object typeEnvs = ReflectionProvider.getField(enter, "typeEnvs");
```

This looks up `javac.enter.typeEnvs` which is needed to create the `Env<AttrContext>` (which is what the Mutator needs to mutate stuff). For some reason, this is coming back `null`.

**Comment by bkushigian** [comment]
This is an error with Major (reproduced without Gradle build)
