### ISSUE TITLE
Failing Test in SpringBoot

### ISSUE THREAD

**Issue by bkushigian** [bkushigian/major-gradle-plugin#6]
After adapting the Spring Boot project to run with the Major Gradle Plugin and building `spring-boot-actuator-autoconfigure` sub project via:

```
./gradlew :spring-boot-project:spring-boot-actuator-autoconfigure:build
```

I get the following error output from Gradle:
```
> Task :spring-boot-project:spring-boot-actuator-autoconfigure:test

ReactiveCloudFoundryActuatorAutoConfigurationTests > skipSslValidation() FAILED
    org.springframework.web.reactive.function.client.WebClientRequestException at ExchangeFunctions.java:137
        Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException at DnsResolveContext.java:1013
2020-12-07 14:46:56.247  INFO 1097 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-14 - Shutdown initiated...
2020-12-07 14:46:56.256  INFO 1097 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-14 - Shutdown completed.
2020-12-07 14:46:56.265  INFO 1097 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2020-12-07 14:46:56.265  INFO 1097 --- [extShutdownHook] o.s.i.channel.PublishSubscribeChannel    : Channel 'application.errorChannel' has 0 subscriber(s).
2020-12-07 14:46:56.265  INFO 1097 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer       : stopped bean '_org.springframework.integration.errorLogger'
2020-12-07 14:46:56.265  INFO 1097 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-12-07 14:46:56.266  INFO 1097 --- [extShutdownHook] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:b728aa20-6331-464e-a4d5-fcaad527965f;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
2020-12-07 14:46:56.266  INFO 1097 --- [extShutdownHook] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:e65b7dba-621a-46cc-b0f3-6172abbdd910;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'

1090 tests completed, 1 failed

> Task :spring-boot-project:spring-boot-actuator-autoconfigure:test FAILED

Found test failures in 1 test task:

:spring-boot-project:spring-boot-actuator-autoconfigure:test
    org.springframework.boot.actuate.autoconfigure.cloudfoundry.reactive.ReactiveCloudFoundryActuatorAutoConfigurationTests > skipSslValidation()

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-boot-project:spring-boot-actuator-autoconfigure:test'.
> There were failing tests. See the report at: file:///Users/benku/Major/test-repos/spring-boot/spring-boot-project/spring-boot-actuator-autoconfigure/build/reports/tests/test/index.html
```

The Gradle report:

```
skipSslValidation()

org.springframework.web.reactive.function.client.WebClientRequestException: Search domain query failed. Original hostname: 'self-signed.badssl.com' failed to resolve 'self-signed.badssl.com.Home' after 4 queries ; nested exception is io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'self-signed.badssl.com' failed to resolve 'self-signed.badssl.com.Home' after 4 queries 
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137)
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'self-signed.badssl.com' failed to resolve 'self-signed.badssl.com.Home' after 4 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:625)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:458)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:201)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:193)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bkushigian** [comment]
Looking at the failing test:
```java

	@Test
	void skipSslValidation() {
		this.contextRunner.withConfiguration(AutoConfigurations.of(HealthEndpointAutoConfiguration.class))
				.withPropertyValues("VCAP_APPLICATION:---", "vcap.application.application_id:my-app-id",
						"vcap.application.cf_api:https://my-cloud-controller.com",
						"management.cloudfoundry.skip-ssl-validation:true")
				.run((context) -> {
					CloudFoundryWebFluxEndpointHandlerMapping handlerMapping = getHandlerMapping(context);
					Object interceptor = ReflectionTestUtils.getField(handlerMapping, "securityInterceptor");
					Object interceptorSecurityService = ReflectionTestUtils.getField(interceptor,
							"cloudFoundrySecurityService");
					WebClient webClient = (WebClient) ReflectionTestUtils.getField(interceptorSecurityService,
							"webClient");
					webClient.get().uri("https://self-signed.badssl.com/").retrieve().toBodilessEntity()
							.block(Duration.ofSeconds(30));
				});
	}
```

Changing the last line to
```
							.block(Duration.ofSeconds(90));
```
fixes the problem: looks like there is just a runtime slowdown from the instrumented code?
